Make local reification aware of GADT type variable binder ordering
goldfirere/th-desugar pull request #173
Opened 2022-11-11 23:17 UTC by RyanGlScott

This is implemented by remembering the explicit `forall` in a GADT constructor's type signature (if one exists) in `RecSelGADT` and using it later to construct the record selector's type signature.

Fixes #171.

2022-11-18 21:40 UTC, goldfirere requested changes

2022-11-18 21:40 UTC, goldfirere commented on Language/Haskell/TH/Desugar/Reify.hs
> +                  Just con_tvbs -> con_tvbs
I think this list can be too long.

For example, if we have

```hs
data G a where
  MkG :: forall a b. { x :: a, y :: b } -> G a
```

then we have

```
ghci> :t x
x :: forall a. G a -> a
```

with `-fprint-explicit-foralls`. So I think this list needs to be thinned to contain only those variables free in the result or field. (Of course, if the latter isn't a subset of the former, we have other problems.) You could do this thinning either here or when the list is stored.

2022-11-19 00:47 UTC, RyanGlScott commented on Language/Haskell/TH/Desugar/Reify.hs
> +                  Just con_tvbs -> con_tvbs
Great catch, I had forgotten entirely about naughty record selectors. I have fixed this oversight and augmented the test case to ensure that this is accounted for.

2022-11-20 19:08 UTC, goldfirere approved these changes

2022-11-20 19:27 UTC, merged