Define `toposortKindVarsOfTvbs`, use it to fix #188
goldfirere/th-desugar pull request #189
Opened 2023-06-25 01:39 UTC by RyanGlScott

`toposortKindVarsOfTvbs` ensures that type variables bound earlier in a telescope do not get returned as free variables, thereby fixing the issue observed in #188.

2023-06-29 22:39 UTC, goldfirere requested changes

2023-06-29 22:39 UTC, goldfirere commented on Language/Haskell/TH/Desugar/Core.hs
> +  L.deleteFirstsBy
This isn't guaranteed to always work. What if you have `forall (a1 :: a2) (a2 :: a1). blah`? This has `a2` free and then binds another `a2` that shadows whatever was already in scope. For names as generated by TH, I think this is probably OK (because those names have uniques), but if there are names generated by `mkName`, I think this won't quite work. I don't think there's a way other than doing some kind of fold.

2023-06-29 22:39 UTC, goldfirere commented on Language/Haskell/TH/Desugar/Core.hs
> +  L.deleteFirstsBy
(A reasonable response is to say that we don't care about the `mkName` case, but then do document the infelicity.)

2023-06-29 23:39 UTC, RyanGlScott commented on Language/Haskell/TH/Desugar/Core.hs
> +  L.deleteFirstsBy
Good catch. I suppose `toposortKindVarsOfTvbs [(a1 :: a2), (a2 :: a1)]` should just return `[a2]`? If so, I think the following implementation would suffice:

```hs
toposortKindVarsOfTvbs tvbs =
  foldr (\tvb kvs ->
          foldMap (\t -> toposortTyVarsOf [t]) (extractTvbKind tvb) ++
          L.deleteBy ((==) `on` dtvbName) tvb kvs)
        []
        (changeDTVFlags () tvbs)
```

I'll push a version that uses this.

2023-07-07 18:07 UTC, goldfirere approved these changes

2023-07-09 11:53 UTC, merged